[metrics]
go_process = true
enable = false

[api]
address = ":5097"
callback_secret = "supersecret"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/pretium_ramp"

[kvvise]
endpoint = ""
api_key = ""

[pretium]
api_key = ""
callback_url = ""
settlement_address = ""

[jetstream]
endpoint = "nats://192.168.1.14:4222"
consumer_id = "pretium-ramp-1"
